/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uam.mx.ayd.proyecto.presentacion;

import java.awt.event.WindowEvent;
import uam.mx.ayd.proyecto.modelo.Modelo;
import uam.mx.ayd.proyecto.negocio.ControlRevisionInventario;

/**
 *
 * @author elxris
 */
public class VentanaRevisionInventario extends javax.swing.JFrame {

    ControlRevisionInventario control;

    /**
     * Creates new form VentanaRevisionInventario
     */
    public VentanaRevisionInventario(ControlRevisionInventario control) {
        initComponents();
        this.control = control;
        actualizaProductoMostrado();
    }

    public void actualizaProductoMostrado() {
        jLabelPerdidas.setText(String.valueOf(control.damePerdida()));
        if (!control.haySiguiente()) {
            jLabelInformacionModelo.setText("No hay más modelos a revisar");
            jLabelPiezasRegistradas.setText("");
            jSpinnerPiezas.setValue(0);
            jSpinnerPiezas.setEnabled(false);
            jButtonSiguiente.setEnabled(false);
            return;
        }
        Modelo modelo = control.siguiente();
        jLabelInformacionModelo.setText(modelo.toString());
        jLabelPiezasRegistradas.setText(String.valueOf(modelo.getNumeropzs()));
        jSpinnerPiezas.setValue(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPiezasRegistradasTitulo = new javax.swing.JLabel();
        jLabelPiezasRegistradas = new javax.swing.JLabel();
        jLabelInformacionModeloTitulo = new javax.swing.JLabel();
        jLabelInformacionModelo = new javax.swing.JLabel();
        jLabelPerdidasTitle = new javax.swing.JLabel();
        jLabelPerdidas = new javax.swing.JLabel();
        jSpinnerPiezas = new javax.swing.JSpinner();
        jLabelPiezasTitle = new javax.swing.JLabel();
        jButtonSiguiente = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonTerminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Revisión Inventario");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabelPiezasRegistradasTitulo.setText("Piezas Registradas:");

        jLabelPiezasRegistradas.setText("####");

        jLabelInformacionModeloTitulo.setText("Información del Modelo:");

        jLabelInformacionModelo.setText("[Información del Modelo]");

        jLabelPerdidasTitle.setText("Pérdidas hasta el momento:");

        jLabelPerdidas.setText("$$$$$");

        jLabelPiezasTitle.setText("Piezas Reales:");

        jButtonSiguiente.setText("Siguiente");
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonTerminar.setText("Terminar y Guardar");
        jButtonTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTerminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelInformacionModeloTitulo)
                    .addComponent(jLabelInformacionModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPerdidasTitle)
                            .addComponent(jLabelPiezasRegistradasTitulo)
                            .addComponent(jLabelPiezasTitle))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinnerPiezas)
                            .addComponent(jLabelPiezasRegistradas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelPerdidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jButtonSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelInformacionModeloTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelInformacionModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPiezasRegistradasTitulo)
                    .addComponent(jLabelPiezasRegistradas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPerdidasTitle)
                    .addComponent(jLabelPerdidas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerPiezas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPiezasTitle))
                .addGap(18, 18, 18)
                .addComponent(jButtonSiguiente)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonTerminar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteActionPerformed
        // TODO add your handling code here:
        control.verificaProductoActual((int) jSpinnerPiezas.getValue());
        actualizaProductoMostrado();
    }//GEN-LAST:event_jButtonSiguienteActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void jButtonTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTerminarActionPerformed
        // TODO add your handling code here:
        control.confirmaReporte();
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_jButtonTerminarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JButton jButtonTerminar;
    private javax.swing.JLabel jLabelInformacionModelo;
    private javax.swing.JLabel jLabelInformacionModeloTitulo;
    private javax.swing.JLabel jLabelPerdidas;
    private javax.swing.JLabel jLabelPerdidasTitle;
    private javax.swing.JLabel jLabelPiezasRegistradas;
    private javax.swing.JLabel jLabelPiezasRegistradasTitulo;
    private javax.swing.JLabel jLabelPiezasTitle;
    private javax.swing.JSpinner jSpinnerPiezas;
    // End of variables declaration//GEN-END:variables
}
