/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uam.mx.ayd.proyecto.presentacion;

import java.awt.event.WindowEvent;
import uam.mx.ayd.proyecto.Aplicacion;

/**
 *
 * @author elxris
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    Aplicacion aplicacion;
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal(Aplicacion a) {
        initComponents();
        aplicacion = a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonConsultarPrecios = new javax.swing.JButton();
        jButtonRealizarVenta = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuInventario = new javax.swing.JMenu();
        jMenuItemRevisarInventario = new javax.swing.JMenuItem();
        jMenuItemStockMuerto = new javax.swing.JMenuItem();
        jMenuItemPrecioCantidad = new javax.swing.JMenuItem();
        jMenuItemAdministrarCatalogo = new javax.swing.JMenuItem();
        jMenuAdministracion = new javax.swing.JMenu();
        jMenuItemAdministraEmpleados = new javax.swing.JMenuItem();
        jMenuItemReporteGanancias = new javax.swing.JMenuItem();
        jMenuItemPlanificacionPromos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jButtonConsultarPrecios.setText("Consultar Precios");

        jButtonRealizarVenta.setText("Realizar Venta");

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jMenuInventario.setText("Inventario");

        jMenuItemRevisarInventario.setText("Revisar Inventario");
        jMenuItemRevisarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRevisarInventarioActionPerformed(evt);
            }
        });
        jMenuInventario.add(jMenuItemRevisarInventario);

        jMenuItemStockMuerto.setText("Consultar Stock Muerto");
        jMenuItemStockMuerto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemStockMuertoActionPerformed(evt);
            }
        });
        jMenuInventario.add(jMenuItemStockMuerto);

        jMenuItemPrecioCantidad.setText("Definir Precio-Cantidad");
        jMenuInventario.add(jMenuItemPrecioCantidad);

        jMenuItemAdministrarCatalogo.setText("Administrar Catalogo");
        jMenuInventario.add(jMenuItemAdministrarCatalogo);

        jMenuBar.add(jMenuInventario);

        jMenuAdministracion.setText("Administración");

        jMenuItemAdministraEmpleados.setText("Administra Empleados");
        jMenuAdministracion.add(jMenuItemAdministraEmpleados);

        jMenuItemReporteGanancias.setText("Reporte Ganancias");
        jMenuAdministracion.add(jMenuItemReporteGanancias);

        jMenuItemPlanificacionPromos.setText("Planificación Promos");
        jMenuAdministracion.add(jMenuItemPlanificacionPromos);

        jMenuBar.add(jMenuAdministracion);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(jButtonConsultarPrecios, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jButtonRealizarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConsultarPrecios, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRealizarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemRevisarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRevisarInventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemRevisarInventarioActionPerformed

    private void jMenuItemStockMuertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemStockMuertoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemStockMuertoActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultarPrecios;
    private javax.swing.JButton jButtonRealizarVenta;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JMenu jMenuAdministracion;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuInventario;
    private javax.swing.JMenuItem jMenuItemAdministraEmpleados;
    private javax.swing.JMenuItem jMenuItemAdministrarCatalogo;
    private javax.swing.JMenuItem jMenuItemPlanificacionPromos;
    private javax.swing.JMenuItem jMenuItemPrecioCantidad;
    private javax.swing.JMenuItem jMenuItemReporteGanancias;
    private javax.swing.JMenuItem jMenuItemRevisarInventario;
    private javax.swing.JMenuItem jMenuItemStockMuerto;
    // End of variables declaration//GEN-END:variables
}
